CREATE TABLE Base.%%ENTITY_TABLE_NAME%%
(
     LoadId INT NOT NULL
    ,LoadDateTime DATETIME NOT NULL
    ,FileName VARCHAR(100) NOT NULL  
    %%COLUMN_LIST_WITH_DATATYPES%%
    %%SCD_2_HASH%%
)
